const GREEN = 65
const RED = 83
const YELLOW = 68
const BLUE = 74
const ORANGE = 75
const NOTE_W = 80
const NOTE_H = 30
const NOTE_VY = 5
const notesDisplay = document.getElementById("notes-display")
const FRETY = document.getElementById("game").height - 40